FROM ubuntu-jdk:17

MAINTAINER Thomas Maestas "thomas.maestas@hotmail.com"

ENV version=1.0.0

ENV dbuser=thomas
ENV dbpassword=${ORACLE_DB_PASSWORD}
ENV jdbcurl=jdbc:oracle:thin:@thomas.cmcadlepsyx9.us-east-1.rds.amazonaws.com:1521:thomas

WORKDIR /usr/local/bin

ADD target/friendsofgroot.war .

ENTRYPOINT ["java", "-jar", "friendsofgroot.war"]
