FROM ubuntu-jdk

MAINTAINER Thomas Maestas "thomas.maestas@hotmail.com"

ENV version=localhost

ENV dbuser=root
ENV dbpass=password
ENV jdbcurl=jdbc:mysql://localhost:3306/groot

WORKDIR /usr/local/bin

ADD "target/friendsofgroot.war" .

ENTRYPOINT ["java", "-jar", "friendsofgroot.war"]
