-- INSERT userS			

Insert into USERS (USERID,USERNAME,PASSWORD,LASTNAME,FIRSTNAME,GROUPS,USERTYPE,PHONE,EMAIL,CUSURL,PHOTOPATH,USERGROUP,ISACTIVE,CONTACTTYPE,ID) values (nextval('ID_MAKER'),'user4@cryptomaven.xyz','password','Smith','Tom',3,1,'5055087707','user1@cryptomaven.xyz','http://www.dailytech.net','photoPath','userGroup',0,1,'1');
Insert into USERS (USERID,USERNAME,PASSWORD,LASTNAME,FIRSTNAME,GROUPS,USERTYPE,PHONE,EMAIL,CUSURL,PHOTOPATH,USERGROUP,ISACTIVE,CONTACTTYPE,ID) values (nextval('ID_MAKER'),'testtest178','passwordX','Smith','Tom',3,1,         '5055087707','user2@cryptomaven.xyz','http://www.dailytech.net','photoPath','userGroup',0,1,'1');
Insert into USERS (USERID,USERNAME,PASSWORD,LASTNAME,FIRSTNAME,GROUPS,USERTYPE,PHONE,EMAIL,CUSURL,PHOTOPATH,USERGROUP,ISACTIVE,CONTACTTYPE,ID) values (nextval('ID_MAKER'),'testtest648','passwordX','Smith','Tom',3,1,         '5055087707','user3@cryptomaven.xyz','http://www.dailytech.net','photoPath','userGroup',0,1,'1');
Insert into USERS (USERID,USERNAME,PASSWORD,LASTNAME,FIRSTNAME,GROUPS,USERTYPE,PHONE,EMAIL,CUSURL,PHOTOPATH,USERGROUP,ISACTIVE,CONTACTTYPE,ID) values (nextval('ID_MAKER'),'u152011',null,'Smith','Tom',0,0,                    '5055087707','user4@cryptomaven.xyz',null, 'photoPath',null,0,0,'5');
Insert into USERS (USERID,USERNAME,PASSWORD,LASTNAME,FIRSTNAME,GROUPS,USERTYPE,PHONE,EMAIL,CUSURL,PHOTOPATH,USERGROUP,ISACTIVE,CONTACTTYPE,ID) values (nextval('ID_MAKER'),'me','pass','maestas22','thomas22',4,2,             '999-999-9999', 'me5@cryptomaven.xyz', 'http://www.dailytech.net','photoPath','userGroup',0,1,'1');
Insert into USERS (USERID,USERNAME,PASSWORD,LASTNAME,FIRSTNAME,GROUPS,USERTYPE,PHONE,EMAIL,CUSURL,PHOTOPATH,USERGROUP,ISACTIVE,CONTACTTYPE,ID) values (nextval('ID_MAKER'),'testtest679','passwordX','Smith','Tom',3,1,         '5055087707','user6@cryptomaven.xyz','http://www.dailytech.net','photoPath','userGroup',0,1,'1');
Insert into USERS (USERID,USERNAME,PASSWORD,LASTNAME,FIRSTNAME,GROUPS,USERTYPE,PHONE,EMAIL,CUSURL,PHOTOPATH,USERGROUP,ISACTIVE,CONTACTTYPE,ID) values (nextval('ID_MAKER'),'testtest562','passwordX','Smith','Tom',3,1,         '5055087707','user7@cryptomaven.xyz','http://www.dailytech.net','photoPath','userGroup',0,1,'5');
Insert into USERS (USERID,USERNAME,PASSWORD,LASTNAME,FIRSTNAME,GROUPS,USERTYPE,PHONE,EMAIL,CUSURL,PHOTOPATH,USERGROUP,ISACTIVE,CONTACTTYPE,ID) values (nextval('ID_MAKER'),'thomas','pass','maestas','thomas',4,2,              '999-999-9999','thomas@cryptomaven.xyz','http://www.dailytech.net','photoPath','userGroup',0,1,'1');
Insert into USERS (USERID,USERNAME,PASSWORD,LASTNAME,FIRSTNAME,GROUPS,USERTYPE,PHONE,EMAIL,CUSURL,PHOTOPATH,USERGROUP,ISACTIVE,CONTACTTYPE,ID) values (nextval('ID_MAKER'),'testtest127','passwordX','Smith','Tom',3,1,         '5055087707','user8@cryptomaven.xyz','http://www.dailytech.net','photoPath','userGroup',0,1,'1');
Insert into USERS (USERID,USERNAME,PASSWORD,LASTNAME,FIRSTNAME,GROUPS,USERTYPE,PHONE,EMAIL,CUSURL,PHOTOPATH,USERGROUP,ISACTIVE,CONTACTTYPE,ID) values (nextval('ID_MAKER'),'testtest201','passwordX','Smith','Tom',3,1,         '5055087707','user8@cryptomaven.xyz','http://www.dailytech.net','photoPath','userGroup',0,1,'1');
Insert into USERS (USERID,USERNAME,PASSWORD,LASTNAME,FIRSTNAME,GROUPS,USERTYPE,PHONE,EMAIL,CUSURL,PHOTOPATH,USERGROUP,ISACTIVE,CONTACTTYPE,ID) values (nextval('ID_MAKER'),'user0ee',null,null,null,0,0,                          '5055087707','thomasm1.maestas@gmail.com', null,'photoPath',null,0,0,null);
Insert into USERS (USERID,USERNAME,PASSWORD,LASTNAME,FIRSTNAME,GROUPS,USERTYPE,PHONE,EMAIL,CUSURL,PHOTOPATH,USERGROUP,ISACTIVE,CONTACTTYPE,ID) values (nextval('ID_MAKER'),'useaa0',null,null,null,0,0,                         '5055087707','admin@gmail.com',null,'photoPath',null,0,0,'520');
Insert into USERS (USERID,USERNAME,PASSWORD,LASTNAME,FIRSTNAME,GROUPS,USERTYPE,PHONE,EMAIL,CUSURL,PHOTOPATH,USERGROUP,ISACTIVE,CONTACTTYPE,ID) values (nextval('ID_MAKER'),'user152013','passwordss','Smith','Tom',3,1,         '5055087707','user152013@cryptomaven.xyz','http://www.dailytech.net','photoPath','userGroup',0,1,'1');
Insert into USERS (USERID,USERNAME,PASSWORD,LASTNAME,FIRSTNAME,GROUPS,USERTYPE,PHONE,EMAIL,CUSURL,PHOTOPATH,USERGROUP,ISACTIVE,CONTACTTYPE,ID) values (nextval('ID_MAKER'),'user152011','passwords22','Smith22','Tom22',3,1,    '5055087707','user152011@cryptomaven.xyz','http://www.dailytech.net','photoPath','userGroup',0,1,'1');
Insert into USERS (USERID,USERNAME,PASSWORD,LASTNAME,FIRSTNAME,GROUPS,USERTYPE,PHONE,EMAIL,CUSURL,PHOTOPATH,USERGROUP,ISACTIVE,CONTACTTYPE,ID) values (nextval('ID_MAKER'),'joshallen','allen','allen','josh',0,0,              '999-999-9999','joshallen8@cryptomaven.xyz', 'http://www.dailytech.net','photoPath','userGroup',0,1,'1');
  Insert into USERS (USERID,USERNAME,PASSWORD,LASTNAME,FIRSTNAME,GROUPS,USERTYPE,PHONE,EMAIL,CUSURL,PHOTOPATH,USERGROUP,ISACTIVE,CONTACTTYPE,ID) values (nextval('ID_MAKER'),'testtest321','passwordX','Smith','Tom',3,1,     '5055087707','user9@cryptomaven.xyz',     'http://www.dailytech.net','photoPath','userGroup',0,1,'1');


-- INSERT CHAIN
Insert into CHAIN (CHAIN_ID,NAME,SYMBOL,DESCRIPTION,LONG_DESCRIPTION,ICON_URL,CATEGORY,CHAIN_LIST_ICON,RPC_URL,  ID,BLOCK_EXPLORER_URL) values (nextval('chain_seq'),'polygon','MATIC_2' ,  'matic  Chain','NFT - 0x1',     'https://s3.amazonaws.com/tmm.net/img/polygon.jpg','Mainnet',null,'https://api.matic.network/ext/bc/C/rpc',2402,null);
Insert into CHAIN (CHAIN_ID,NAME,SYMBOL,DESCRIPTION,LONG_DESCRIPTION,ICON_URL,CATEGORY,CHAIN_LIST_ICON,RPC_URL,  ID,BLOCK_EXPLORER_URL) values (nextval('chain_seq'),'avalanche','avax',    'Avalanche C-Chain','NFT - 0x1','https://s3.amazonaws.com/tmm.net/img/avax.png','Mainnet',null,'https://api.avax.network/ext/bc/C/rpc',3,null);
Insert into CHAIN (CHAIN_ID,NAME,SYMBOL,DESCRIPTION,LONG_DESCRIPTION,ICON_URL,CATEGORY,CHAIN_LIST_ICON,RPC_URL,  ID,BLOCK_EXPLORER_URL) values (nextval('chain_seq'),'pulsechain','pls',    'Pulsechain Mainnet','NFT   0x1','https://s3.amazonaws.com/tmm.net/img/pulsechain.png','Mainnet','https://friends-of-groot-society.s3.amazonaws.com/assets/android-chrome-384x384.png','https://rpc.pulsechain.io',4,null);
Insert into CHAIN (CHAIN_ID,NAME,SYMBOL,DESCRIPTION,LONG_DESCRIPTION,ICON_URL,CATEGORY,CHAIN_LIST_ICON,RPC_URL,  ID,BLOCK_EXPLORER_URL) values (nextval('chain_seq'),'solana','sol',        'solana Mainnet','NFT - 0x1',   'https://s3.amazonaws.com/tmm.net/img/solana.jpg','Mainnet','https://friends-of-groot-society.s3.amazonaws.com/assets/android-chrome-384x384.png','https://api.mainnet-beta.solana.com',3,null);
Insert into CHAIN (CHAIN_ID,NAME,SYMBOL,DESCRIPTION,LONG_DESCRIPTION,ICON_URL,CATEGORY,CHAIN_LIST_ICON,RPC_URL,  ID,BLOCK_EXPLORER_URL) values (nextval('chain_seq'),'polygon','matic',     'Polygon Mainnet','NFT - 0x1',  'https://s3.amazonaws.com/tmm.net/img/polygon.jpg','Mainnet',null,' https://rpc-mainnet.maticvigil.com/',3,null);
Insert into CHAIN (CHAIN_ID,NAME,SYMBOL,DESCRIPTION,LONG_DESCRIPTION,ICON_URL,CATEGORY,CHAIN_LIST_ICON,RPC_URL,  ID,BLOCK_EXPLORER_URL) values (nextval('chain_seq'),'pulseChain','TPLS',   'Pulsechain Mainnet','NFT - 0x1','https://s3.amazonaws.com/tmm.net/img/pulsechain.png','Mainnet',null,'https://rpc.testnet.pulsechain.com',240,null);
Insert into CHAIN (CHAIN_ID,NAME,SYMBOL,DESCRIPTION,LONG_DESCRIPTION,ICON_URL,CATEGORY,CHAIN_LIST_ICON,RPC_URL,  ID,BLOCK_EXPLORER_URL) values (nextval('chain_seq'),'ethereum','ETH23',    'ethereum Mainnet 23','NFT  0x1','https://s3.amazonaws.com/tmm.net/img/ether.png','ethereum2',null,'ETH RPC23',3,null);
Insert into CHAIN (CHAIN_ID,NAME,SYMBOL,DESCRIPTION,LONG_DESCRIPTION,ICON_URL,CATEGORY,CHAIN_LIST_ICON,RPC_URL,  ID,BLOCK_EXPLORER_URL) values (nextval('chain_seq'),'pulsechain','pls',    'Pulsechain Mainnet','NFT - 0x1','https://s3.amazonaws.com/tmm.net/img/pulsechain.png','Mainnet','https://friends-of-groot-society.s3.amazonaws.com/assets/android-chrome-384x384.png','https://rpc.pulsechain.io',4,null);
Insert into CHAIN (CHAIN_ID,NAME,SYMBOL,DESCRIPTION,LONG_DESCRIPTION,ICON_URL,CATEGORY,CHAIN_LIST_ICON,RPC_URL,  ID,BLOCK_EXPLORER_URL) values (nextval('chain_seq'),'pulsechain','pls',    'Pulsechain Mainnet','NFT - 0x1','https://s3.amazonaws.com/tmm.net/img/pulsechain.png','Mainnet','https://friends-of-groot-society.s3.amazonaws.com/assets/android-chrome-384x384.png','https://rpc.pulsechain.io',434,null);
Insert into CHAIN (CHAIN_ID,NAME,SYMBOL,DESCRIPTION,LONG_DESCRIPTION,ICON_URL,CATEGORY,CHAIN_LIST_ICON,RPC_URL,  ID,BLOCK_EXPLORER_URL) values (nextval('chain_seq'),'pulsechain7','pls',   'Pulsechain Mainnet','NFT - 0x1','https://s3.amazonaws.com/tmm.net/img/pulsechain.png','Mainnet','https://friends-of-groot-society.s3.amazonaws.com/assets/android-chrome-384x384.png','https://rpc.pulsechain.io',23,null);
Insert into CHAIN (CHAIN_ID,NAME,SYMBOL,DESCRIPTION,LONG_DESCRIPTION,ICON_URL,CATEGORY,CHAIN_LIST_ICON,RPC_URL,  ID,BLOCK_EXPLORER_URL) values (nextval('chain_seq'),'pulseChain','tPLS',   'PulseChain Testnet 2b','NFT 0x1','https://s3.amazonaws.com/tmm.net/img/pulsechain.png','Mainnet',null,'https://rpc.v2b.testnet.pulsechain.com',3,null);
Insert into CHAIN (CHAIN_ID,NAME,SYMBOL,DESCRIPTION,LONG_DESCRIPTION,ICON_URL,CATEGORY,CHAIN_LIST_ICON,RPC_URL,  ID,BLOCK_EXPLORER_URL) values (nextval('chain_seq'),'pulseChain','TPLS',   'Pulsechain Mainnet','NFT - 0x1', 'https://s3.amazonaws.com/tmm.net/img/pulsechain.png','Mainnet',null,'https://rpc.testnet.pulsechain.com',240,null);
insert into chain (CHAIN_ID,NAME,SYMBOL,DESCRIPTION,LONG_DESCRIPTION,ICON_URL,CATEGORY,CHAIN_LIST_ICON,RPC_URL,  ID,BLOCK_EXPLORER_URL) values (nextval('chain_seq'),'ethereum', 'symbol',  'description', 'longDescription', 'https://s3.amazonaws.com/tmm.net/img/ether.png', 'category', 'chainListIcon', 'rpcUrl', 1, 'blockExplorerUrl');
insert into chain (CHAIN_ID,NAME,SYMBOL,DESCRIPTION,LONG_DESCRIPTION,ICON_URL,CATEGORY,CHAIN_LIST_ICON,RPC_URL,  ID,BLOCK_EXPLORER_URL) values (nextval('chain_seq'),'pulsechain', 'symbol','description', 'longDescription', 'https://s3.amazonaws.com/tmm.net/img/ether.png', 'category', 'chainListIcon', 'rpcUrl', 1, 'blockExplorerUrl');
insert into chain (CHAIN_ID,NAME,SYMBOL,DESCRIPTION,LONG_DESCRIPTION,ICON_URL,CATEGORY,CHAIN_LIST_ICON,RPC_URL,  ID,BLOCK_EXPLORER_URL) values (nextval('chain_seq'),'hex', 'symbol',       'description', 'longDescription', 'https://s3.amazonaws.com/tmm.net/img/ether.png', 'category', 'chainListIcon', 'rpcUrl', 1, 'blockExplorerUrl');
insert into chain (CHAIN_ID,NAME,SYMBOL,DESCRIPTION,LONG_DESCRIPTION,ICON_URL,CATEGORY,CHAIN_LIST_ICON,RPC_URL,  ID,BLOCK_EXPLORER_URL) values (nextval('chain_seq'),'polygon', 'symbol',   'description', 'longDescription', 'https://s3.amazonaws.com/tmm.net/img/polygon.jpg', 'category', 'chainListIcon', 'rpcUrl', 1, 'blockExplorerUrl');
-- INSERT PROJECT_user_RELATION
insert into chain_users (userid, chain_id) (select u.userid, c.chain_id from user u, chain c where u.email ='warton@gmail.com' AND c.name = 'polygon');
insert into chain_users (userid, chain_id) (select u.userid, c.chain_id from user u, chain c where u.email ='lanister@gmail.com' AND c.name = 'ethereum');
insert into chain_users (userid, chain_id) (select u.userid, c.chain_id from user u, chain c where u.email ='Reeves@gmail.com' AND c.name = 'ethereum');
insert into chain_users (userid, chain_id) (select u.userid, c.chain_id from user u, chain c where u.email ='connor@gmail.com' AND c.name = 'polygon');
insert into chain_users (userid, chain_id) (select u.userid, c.chain_id from user u, chain c where u.email ='connor@gmail.com' AND c.name = 'hex');
insert into chain_users (userid, chain_id) (select u.userid, c.chain_id from user u, chain c where u.email ='connor@gmail.com' AND c.name = 'ethereum');
insert into chain_users (userid, chain_id) (select u.userid, c.chain_id from user u, chain c where u.email ='Sal@gmail.com' AND c.name = 'ethereum');
insert into chain_users (userid, chain_id) (select u.userid, c.chain_id from user u, chain c where u.email ='henley@gmail.com' AND c.name = 'ethereum');
insert into chain_users (userid, chain_id) (select u.userid, c.chain_id from user u, chain c where u.email ='connor@gmail.com' AND c.name = 'pulsechain');
insert into chain_users (userid, chain_id) (select u.userid, c.chain_id from user u, chain c where u.email ='Sal@gmail.com' AND c.name = 'pulsechain');
insert into chain_users (userid, chain_id) (select u.userid, c.chain_id from user u, chain c where u.email ='henley@gmail.com' AND c.name = 'pulsechain');
insert into chain_users (userid, chain_id) (select u.userid, c.chain_id from user u, chain c where u.email ='carson@gmail.com' AND c.name = 'polygon ');
insert into chain_users (userid, chain_id) (select u.userid, c.chain_id from user u, chain c where u.email ='miles@gmail.com' AND c.name = 'polygon');
insert into chain_users (userid, chain_id) (select u.userid, c.chain_id from user u, chain c where u.email ='roggers@gmail.com' AND c.name = 'polygon');
insert into chain_users (userid, chain_id) (select u.userid, c.chain_id from user u, chain c where u.email ='carson@gmail.com' AND c.name = 'hex');
insert into chain_users (userid, chain_id) (select u.userid, c.chain_id from user u, chain c where u.email ='miles@gmail.com' AND c.name = 'hex');
insert into chain_users (userid, chain_id) (select u.userid, c.chain_id from user u, chain c where u.email ='roggers@gmail.com' AND c.name = 'hex');


Insert into ADDRESS (ID,ADDRESS,BLOCK_EXPLORER_URL,CHAIN,CHAIN_ID,DESCRIPTION,ICON_URL,OWNER,USER_ID,USERID,NFT_ID,NFT_ADDRESS,EMAIL,NFT_ADDRESS_ID,NFT_ADDRESS_NFT_ADDRESS_ID) values (nextval('address_seq'),'0x900bE021E38B8d08435A03c05657C8cFA837cAeF',null,'ropstein',0,null,null,'thomasm1.maestas@gmail.com',null,null,null,null,null,null,null);
Insert into ADDRESS (ID,ADDRESS,BLOCK_EXPLORER_URL,CHAIN,CHAIN_ID,DESCRIPTION,ICON_URL,OWNER,USER_ID,USERID,NFT_ID,NFT_ADDRESS,EMAIL,NFT_ADDRESS_ID,NFT_ADDRESS_NFT_ADDRESS_ID) values (nextval('address_seq'),null,null,'polygon',0,null,null,'thomasm1.maestas@gmail.com',null,null,null,null,null,null,null);
Insert into ADDRESS (ID,ADDRESS,BLOCK_EXPLORER_URL,CHAIN,CHAIN_ID,DESCRIPTION,ICON_URL,OWNER,USER_ID,USERID,NFT_ID,NFT_ADDRESS,EMAIL,NFT_ADDRESS_ID,NFT_ADDRESS_NFT_ADDRESS_ID) values (nextval('address_seq'),null,null,'polygon',0,null,null,'thomasm1.maestas@gmail.com',null,null,null,null,null,null,null);
Insert into ADDRESS (ID,ADDRESS,BLOCK_EXPLORER_URL,CHAIN,CHAIN_ID,DESCRIPTION,ICON_URL,OWNER,USER_ID,USERID,NFT_ID,NFT_ADDRESS,EMAIL,NFT_ADDRESS_ID,NFT_ADDRESS_NFT_ADDRESS_ID) values (nextval('address_seq'),null,null,'ethereum',0,null,null,'thomasm1.maestas@gmail.com',null,null,null,null,null,null,null);
Insert into ADDRESS (ID,ADDRESS,BLOCK_EXPLORER_URL,CHAIN,CHAIN_ID,DESCRIPTION,ICON_URL,OWNER,USER_ID,USERID,NFT_ID,NFT_ADDRESS,EMAIL,NFT_ADDRESS_ID,NFT_ADDRESS_NFT_ADDRESS_ID) values (nextval('address_seq'),'0x399EEc3B8e889a2E0853dd254f09C4535061693A',null,'polygon',0,null,null,'thomasm1.maestas@gmail.com',null,null,null,null,null,null,null);
Insert into ADDRESS (ID,ADDRESS,BLOCK_EXPLORER_URL,CHAIN,CHAIN_ID,DESCRIPTION,ICON_URL,OWNER,USER_ID,USERID,NFT_ID,NFT_ADDRESS,EMAIL,NFT_ADDRESS_ID,NFT_ADDRESS_NFT_ADDRESS_ID) values (nextval('address_seq'),'0x399EEc3B8e889a2E0853dd254f09C4535061693A',null,'polygon',0,null,null,'thomasm1.maestas@gmail.com',null,null,null,null,null,null,null);
Insert into ADDRESS (ID,ADDRESS,BLOCK_EXPLORER_URL,CHAIN,CHAIN_ID,DESCRIPTION,ICON_URL,OWNER,USER_ID,USERID,NFT_ID,NFT_ADDRESS,EMAIL,NFT_ADDRESS_ID,NFT_ADDRESS_NFT_ADDRESS_ID) values (nextval('address_seq'),'0x399EEc3B8e889a2E0853dd254f09C4535061693A',null,'ropstein',0,null,null,'thomasm1.maestas@gmail.com',null,null,null,null,null,null,null);
Insert into ADDRESS (ID,ADDRESS,BLOCK_EXPLORER_URL,CHAIN,CHAIN_ID,DESCRIPTION,ICON_URL,OWNER,USER_ID,USERID,NFT_ID,NFT_ADDRESS,EMAIL,NFT_ADDRESS_ID,NFT_ADDRESS_NFT_ADDRESS_ID) values (nextval('address_seq'),'0x900bE021E38B8d08435A03c05657C8cFA837cAeF',null,'ethereum',0,null,null,'thomasm1.maestas@gmail.com',null,null,null,null,null,null,null);
Insert into ADDRESS (ID,ADDRESS,BLOCK_EXPLORER_URL,CHAIN,CHAIN_ID,DESCRIPTION,ICON_URL,OWNER,USER_ID,USERID,NFT_ID,NFT_ADDRESS,EMAIL,NFT_ADDRESS_ID,NFT_ADDRESS_NFT_ADDRESS_ID) values (nextval('address_seq'),'0x900bE021E38B8d08435A03c05657C8cFA837cAeF',null,'ethereum',0,null,null,'thomasm1.maestas@gmail.com',null,null,null,null,null,null,null);
Insert into ADDRESS (ID,ADDRESS,BLOCK_EXPLORER_URL,CHAIN,CHAIN_ID,DESCRIPTION,ICON_URL,OWNER,USER_ID,USERID,NFT_ID,NFT_ADDRESS,EMAIL,NFT_ADDRESS_ID,NFT_ADDRESS_NFT_ADDRESS_ID) values (nextval('address_seq'),'0x900bE021E38B8d08435A03c05657C8cFA837cAeF',null,'polygon',0,null,null,'thomasm1.maestas@gmail.com',null,null,null,null,null,null,null);
Insert into ADDRESS (ID,ADDRESS,BLOCK_EXPLORER_URL,CHAIN,CHAIN_ID,DESCRIPTION,ICON_URL,OWNER,USER_ID,USERID,NFT_ID,NFT_ADDRESS,EMAIL,NFT_ADDRESS_ID,NFT_ADDRESS_NFT_ADDRESS_ID) values (nextval('address_seq'),'0x399EEc3B8e889a2E0853dd254f09C4535061693A',null,'goerli',0,null,null,'thomasm1.maestas@gmail.com',null,null,null,null,null,null,null);
Insert into ADDRESS (ID,ADDRESS,BLOCK_EXPLORER_URL,CHAIN,CHAIN_ID,DESCRIPTION,ICON_URL,OWNER,USER_ID,USERID,NFT_ID,NFT_ADDRESS,EMAIL,NFT_ADDRESS_ID,NFT_ADDRESS_NFT_ADDRESS_ID) values (nextval('address_seq'),'0x900bE021E38B8d08435A03c05657C8cFA837cAeF',null,'ethereum',0,null,null,'thomasm1.maestas@gmail.com',null,null,null,null,null,null,null);
Insert into ADDRESS (ID,ADDRESS,BLOCK_EXPLORER_URL,CHAIN,CHAIN_ID,DESCRIPTION,ICON_URL,OWNER,USER_ID,USERID,NFT_ID,NFT_ADDRESS,EMAIL,NFT_ADDRESS_ID,NFT_ADDRESS_NFT_ADDRESS_ID) values (nextval('address_seq'),'0x399EEc3B8e889a2E0853dd254f09C4535061693A',null,'polygon',0,null,null,'thomasm1.maestas@gmail.com',null,null,null,625,null,null,null);
Insert into ADDRESS (ID,ADDRESS,BLOCK_EXPLORER_URL,CHAIN,CHAIN_ID,DESCRIPTION,ICON_URL,OWNER,USER_ID,USERID,NFT_ID,NFT_ADDRESS,EMAIL,NFT_ADDRESS_ID,NFT_ADDRESS_NFT_ADDRESS_ID) values (nextval('address_seq'), 'address','blockExplorerUrl','chain',0,'description','iconUrl','owner',null,null,null,null,null,null,null);
Insert into ADDRESS (ID,ADDRESS,BLOCK_EXPLORER_URL,CHAIN,CHAIN_ID,DESCRIPTION,ICON_URL,OWNER,USER_ID,USERID,NFT_ID,NFT_ADDRESS,EMAIL,NFT_ADDRESS_ID,NFT_ADDRESS_NFT_ADDRESS_ID) values (nextval('address_seq'),'address','blockExplorerUrl','chain',0,'description','iconUrl',null,null,null,null,null,'thomasm1.maestas@gmail.com',null,null);
Insert into ADDRESS (ID,ADDRESS,BLOCK_EXPLORER_URL,CHAIN,CHAIN_ID,DESCRIPTION,ICON_URL,OWNER,USER_ID,USERID,NFT_ID,NFT_ADDRESS,EMAIL,NFT_ADDRESS_ID,NFT_ADDRESS_NFT_ADDRESS_ID) values (nextval('address_seq'),'address','blockExplorerUrl','chain',0,'description','iconUrl',null,null,null,null,null,'thomasm1.___________________maestas@gmail.com',null,null);
Insert into ADDRESS (ID,ADDRESS,BLOCK_EXPLORER_URL,CHAIN,CHAIN_ID,DESCRIPTION,ICON_URL,OWNER,USER_ID,USERID,NFT_ID,NFT_ADDRESS,EMAIL,NFT_ADDRESS_ID,NFT_ADDRESS_NFT_ADDRESS_ID) values (nextval('address_seq'),' 0xc8d6A88EF3627C7B666117Da5F6d23Ac0B01b156',null,'fantom',0,null,null,'thomas1.maestas@gmail.com',null,null,null,null,null,null,null);
Insert into ADDRESS (ID,ADDRESS,BLOCK_EXPLORER_URL,CHAIN,CHAIN_ID,DESCRIPTION,ICON_URL,OWNER,USER_ID,USERID,NFT_ID,NFT_ADDRESS,EMAIL,NFT_ADDRESS_ID,NFT_ADDRESS_NFT_ADDRESS_ID) values (nextval('address_seq'),' 0xc8d6A88EF3627C7B666117Da5F6d23Ac0B01b156',null,'arbitrum',0,null,null,'thomas1.maestas@gmail.com',null,null,null,null,null,null,null);

Insert into COINTABLE (COINID,COINTOKEN,COINSYMBOL,PRICETOTAL,PURCHASED) values (nextval('cointable_seq'),'Ethereum','ETH',12000.22,0);
Insert into COINTABLE (COINID,COINTOKEN,COINSYMBOL,PRICETOTAL,PURCHASED) values (nextval('cointable_seq'),'POLYGON','MATIC',9.22,0);
Insert into COINTABLE (COINID,COINTOKEN,COINSYMBOL,PRICETOTAL,PURCHASED) values (nextval('cointable_seq'),'BINANCE','BNB',19.22,0);
Insert into COINTABLE (COINID,COINTOKEN,COINSYMBOL,PRICETOTAL,PURCHASED) values (nextval('cointable_seq'),'AVALANCHE','AVAX',119.22,0);
Insert into COINTABLE (COINID,COINTOKEN,COINSYMBOL,PRICETOTAL,PURCHASED) values (nextval('cointable_seq'),'Ethereum','ETH',45000,0);
Insert into COINTABLE (COINID,COINTOKEN,COINSYMBOL,PRICETOTAL,PURCHASED) values (nextval('cointable_seq'),'Ethereum','ETH',45000,0);
Insert into COINTABLE (COINID,COINTOKEN,COINSYMBOL,PRICETOTAL,PURCHASED) values (nextval('cointable_seq'),'Ethereum','ETH',45000,0);
Insert into COINTABLE (COINID,COINTOKEN,COINSYMBOL,PRICETOTAL,PURCHASED) values (nextval('cointable_seq'),'Ethereum','ETH',45000,0);
Insert into COINTABLE (COINID,COINTOKEN,COINSYMBOL,PRICETOTAL,PURCHASED) values (nextval('cointable_seq'),'saa','SAA',123.33,0);
Insert into COINTABLE (COINID,COINTOKEN,COINSYMBOL,PRICETOTAL,PURCHASED) values (nextval('cointable_seq'),'Ethereum','ETH',45000,0);
Insert into COINTABLE (COINID,COINTOKEN,COINSYMBOL,PRICETOTAL,PURCHASED) values (nextval('cointable_seq'),'Ethereum','ETH',45000,0);
Insert into COINTABLE (COINID,COINTOKEN,COINSYMBOL,PRICETOTAL,PURCHASED) values (nextval('cointable_seq'),'Hex','HEX',0.03,1);
Insert into COINTABLE (COINID,COINTOKEN,COINSYMBOL,PRICETOTAL,PURCHASED) values (nextval('cointable_seq'),'Ethereum','ETH',45000,0);
Insert into COINTABLE (COINID,COINTOKEN,COINSYMBOL,PRICETOTAL,PURCHASED) values (nextval('cointable_seq'),'Binance','bsc',45000,0);
Insert into COINTABLE (COINID,COINTOKEN,COINSYMBOL,PRICETOTAL,PURCHASED) values (nextval('cointable_seq'),'binance','bnb',45000,0);

INSERT INTO NFT (ID,NAME,AMOUNT,METADATA_ID,NFT_ADDRESS_ID) VALUES (nextval('nft_seq'),'ethereum',11,1,1);
INSERT INTO NFT (ID,NAME,AMOUNT,METADATA_ID,NFT_ADDRESS_ID) VALUES (nextval('nft_seq'),'POLYGON',11,1,1);
INSERT INTO NFT (ID,NAME,AMOUNT,METADATA_ID,NFT_ADDRESS_ID) VALUES (nextval('nft_seq'),'avalanche',11,1,1);
INSERT INTO NFT (ID,NAME,AMOUNT,METADATA_ID,NFT_ADDRESS_ID) VALUES (nextval('nft_seq'),'ethereum',11,1,1);
INSERT INTO NFT (ID,NAME,AMOUNT,METADATA_ID,NFT_ADDRESS_ID) VALUES (nextval('nft_seq'),'pulsechain',11,1,1);