create table if not exists user (
 USERID int auto_increment primary key,
	USERNAME VARCHAR(60 ),
	PASSWORD VARCHAR(20 ),
	LASTNAME VARCHAR(60 ),
	FIRSTNAME VARCHAR(60 ),
	GROUPS int ,
	USERTYPE int,
	PHONE VARCHAR(50 ),
	EMAIL VARCHAR(30 ),
	CUSURL VARCHAR(100 ),
	PHOTOPATH VARCHAR(400 ),
	USERGROUP VARCHAR(100 ),
	ISACTIVE TINYINT,
	CONTACTTYPE int,
	ID VARCHAR(50  )
);

   